// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  serialize

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AnalysisResult ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AnalysisResult ) UnmarshalJSON([]byte) error { return nil }
func ( AnalysisResult ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AnalysisResult ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AnalysisResult *AnalysisResult

func ( PostScanSpec ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostScanSpec ) UnmarshalJSON([]byte) error { return nil }
func ( PostScanSpec ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostScanSpec ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostScanSpec *PostScanSpec

func ( Result ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Result ) UnmarshalJSON([]byte) error { return nil }
func ( Result ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Result ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Result *Result

func ( Results ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Results ) UnmarshalJSON([]byte) error { return nil }
func ( Results ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Results ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Results *Results

func ( StringSlice ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* StringSlice ) UnmarshalJSON([]byte) error { return nil }
func ( StringSlice ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* StringSlice ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_StringSlice *StringSlice
